import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import { LanguageProvider } from "@/lib/i18n/LanguageContext";
import Navigation from "@/components/sections/navigation";
import Footer from "@/components/sections/footer";
import { Toaster } from 'react-hot-toast';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <LanguageProvider>
          <Navigation />  
          <ErrorReporter />
          <Toaster position="bottom-right" reverseOrder={false} />
          {children}
          <VisualEditsMessenger />
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}